# This is the settings file, used when running the server with `chain run`,
# Here you can define the jvm options, server args, and files to copy/override.
# This file can also be duplicated as 'settings.dev.yml', and have different values,
# Useful for values or files only meant for development

# This is the command or path to the java binary (Optional, defaults to 'java')
java-runtime: java

# Options to pass to the JVM (Optional)
jvm-options:
  - "-Dfile.encoding=UTF-8"
  - "-Xmx4G"

# Arguments to pass to the server (Optional)
server-args:
  - "--nogui"

# Here you can define the files/folders to copy/override when running the server,
# Like server or plugin config files (Optional)
files:
  # The key is a path to a file/folder within the server directory,
  # And the value is a path to a file/folder relative to the root directory (where the chain.yml file is located)
  'server.properties': "config/server.properties"
