[package]
name = "chain"
version = "0.1.0"
description = "Make your Minecraft Servers VCS friendly"
edition = "2021"
publish = false
license = "MIT"
authors = ["Zeke <ezequiel_io@pm.me>"]
homepage = "https://github.com/zeke-io/chain"
repository = "https://github.com/zeke-io/chain"

[package.metadata.deb]
maintainer = "Zeke <ezequiel_io@pm.me>"
copyright = "2023 <ezequiel_io@pm.me>"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.4", features = ["derive"] }
crossterm = "0.26.1"
inquire = "0.6.2"
regex = "1.9.1"
reqwest = "0.11.18"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.25"
tokio = { version = "1", features = ["full"] }
url = "2.4.0"
walkdir = "2.3.3"
zip = "0.6.6"
