[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
colog = "1.3.0"
project.workspace = true
templater.workspace = true
tokio = { version = "1", features = ["full"] }
