jvm-options:
  - "-Xmx1G"

env:
  CHAIN_HOST: 127.0.0.1
  CHAIN_PORT: 25565
  CHAIN_FORWARDING_SECRET: SECRET-AsfQRit

files:
  'forwarding.secret': config/forwarding.secret
  'velocity.toml': config/velocity.toml

