[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
log.workspace = true
reqwest.workspace = true
serde_json = "1"
serde = { version = "1.0.197", features = ["derive"] }
utils.workspace = true
