[package]
name = "common"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.71"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.7.6"
