[package]
name = "common"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.71"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.25"
