[package]
name = "core"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.71"
reqwest = "0.11.18"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.25"
url = "2.4.0"
